### PR TITLE
Add new project(Spin) in JS 

### PR DESCRIPTION
**Pull request by Harsh2220**

### CODE REVIEW

**Comment by Atharv-Attri** [comment]
Can you explain what this does?

**Comment by Harsh2220** [comment]
It is a spin the wheel .

**Comment by Atharv-Attri** [comment]
Ok, I'll merge!

**Comment by Harsh2220** [comment]
Thanks !!

**Comment by Harsh2220** [comment]
please add,
Label = hacktoberfest-accepted and
Topic = hacktoberfest

**Comment by Atharv-Attri** [comment]
I already have the hacktoberfest topic on the repo, so it should already count

**Pull request merged**
