### PR TITLE
Create Number guessing Game.cpp

### PR DESCRIPTION
**Pull request by Aarhan212**

### CODE REVIEW

**Comment by Atharv-Attri** [comment]
@Aarhan212 I feel that this does not meet our quality standards. Please see if you can improve it in any way by making it more complex or something.

**Comment by Aarhan212** [comment]
ohh really sorry for that even though i read the guildlines . I will try to improve it .

**Comment by Atharv-Attri** [comment]
No problem, everyone makes mistakes, glad you choose to go back and improve it!

**Comment by Aarhan212** [comment]
what should i do make it a more complex or add few more games , because i read the guildlines , there it was written, a basic do while loop and few if else statements will work.

**Comment by Atharv-Attri** [comment]
I'm sorry the readme confused you. It says that for the what not to do part. If you look one line down, it says, "However, the following adds more complexity". I will try to make it clearer.

You could try to compare different strategies for the guessing game, like the 50/50 split, the 1-100 linear, the random number, and stuff like that.

**Comment by Aarhan212** [comment]
made some changes

**Comment by Aarhan212** [comment]
hey can you pls clarify if i have to do more changes?
or is it okay

**Comment by Atharv-Attri** [comment]
Sorry for the late response. You still need to make more changes and add complexity. Sorry, but I need to be strict on the quality of what I merge because I do not want this repo to be invalid for DO, and have the hard work of other people go to waste. For an example of quality, please check any closed PRs.

**Comment by Aarhan212** [comment]
sure I can understand , Only one pr left

**Comment by Atharv-Attri** [comment]
Yes, this is good, I'll go ahead and merge it now!

**Comment by Aarhan212** [comment]
thanks

**Pull request merged**
