### PR TITLE
added new project

### PR DESCRIPTION
**Pull request by eswarupkumar**
Build a JS Project i.e stone paper scissor game.

### CODE REVIEW

**Comment by Atharv-Attri** [comment]
You literally deleted every single other file. I will mark this PR as invalid, please create a new one that does not remove these files. Other than that, I'm more than happy to merge!

**Comment by Atharv-Attri** [comment]
Actually, I won't mark it as invalid, I don't want you to get a strike, I'll talk to Matt and see if there is a way I can have this PR not count and still not get you a strike

**Comment by Atharv-Attri** [comment]
Hey, turns out there was an error on the repo that was causing it, can you please re-clone and then add in your files. Sorry for the inconvenience

**Comment by eswarupkumar** [comment]
Okay sure. I didn't delete any. There was problem in cloning maybe.

**Comment by Atharv-Attri** [comment]
Yes, one of the folder names had a space in it, so it was causing errors in git

**Comment by eswarupkumar** [comment]
Unable to clone any files present in the repo. I used the git clone command
and after I did there is no file present inside.

**Comment by Atharv-Attri** [comment]
IDK why that is happening. Can you try doing it all over again from the start? (even deleting the fork)

**Comment by eswarupkumar** [comment]
Thanks. Did what you said. Have a look .

**Comment by Atharv-Attri** [comment]
Well, You are lucky, since I have this repo labeled as hacktoberfest, there is no way I can close this repo without it going against your spam counter, so you get a free PR!

**Comment by eswarupkumar** [comment]
Thank you. This will count as PR for hacktober fest. Isn't?

**Comment by Atharv-Attri** [comment]
Yes it will.

**Pull request closed without merging**
