### PR TITLE
Vigenere cipher

### LINKED ISSUE #13: Project idea: Vigenere Cipher in Python 3
### Create the Vigenere Cipher method to encrypt alphabetic text. 

Checklist:
- [ ] This has not been made in the language I want to make it in
- [x] I 100% believe this  meets quality standards

### PR DESCRIPTION
**Pull request by DavidBanda**
### Closes #13

### CODE REVIEW

**Comment by Atharv-Attri** [comment]
Can you add in some interactivity to make it a little more complex? Other than that, it's ready to be merged!

**Comment by DavidBanda** [comment]
Do you mean on console or with an interface?

**Comment by Atharv-Attri** [comment]
A console should suffice, but if you want to quickly add an interface, you can!

**Comment by DavidBanda** [comment]
Done!

**Comment by Atharv-Attri** [comment]
Merged!

**Pull request merged**
