### PR TITLE
Create Factorial.c

### PR DESCRIPTION
**Pull request by jpedrinhoxd**
A simple code that calculates the factorial of a number

### Tag the issue you made here:
My issue number is: 1

### CODE REVIEW

**Comment by Atharv-Attri** [comment]
There are a few problems here

1. you do not have a valid issue, which you were supposed to make before you started working, but even if I ignore that,
2. Your project is too simple, add more complexity to it. High-quality PRs are a must for us, we do not want other people's hard work to go in vain because DO thinks we don't meet their quality standards

**Comment by Atharv-Attri** [comment]
Here is what you should do: go make an issue so we can work out what is sufficient quality

**Comment by Atharv-Attri** [comment]
Do you wish to continue on this?

**Comment by jpedrinhoxd** [comment]
I forgot to answer, I'm sorry, but I'm not going to continue. Thank you!

**Comment by Atharv-Attri** [comment]
Alright, No Problem!

**Pull request closed without merging**
